
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.3.0
    steps:
      - checkout
      - run: node --version

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build
