version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0
   node: circleci/node@2.0
jobs:
  build:        
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages
      - serverless/setup
      - run: sls deploy 
workflows:
  build_lambda:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
          
